import React, { useState } from 'react';
import { X, Download, FileText, Check, Copy, Sparkles, Award } from 'lucide-react';
import { FullAnalysisResult } from '../../types/photography';

interface ExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  analysis: FullAnalysisResult;
}

export const ExportModal: React.FC<ExportModalProps> = ({
  isOpen,
  onClose,
  analysis
}) => {
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const generateMarkdownReport = (): string => {
    const p1 = analysis.phase1;
    const p2 = analysis.phase2;
    const p3 = analysis.phase3;
    const p4 = analysis.phase4;

    return `# AuraLens Pro — Executive Photography Critique & Transformation Report
**Timestamp:** ${new Date(analysis.timestamp || Date.now()).toLocaleString()}
**Overall Composite Score:** ${p4?.overallScore ?? 75}/100
**Genre:** ${p2?.detectedGenre || 'Photography'} | **Dynamic Range:** ${p3?.dynamicRange || 'Balanced'}

---

## 1. Executive Summary
${p4?.executiveSummary || 'Photographic analysis completed.'}

### Performance Scores:
- **Composition & Balance:** ${p4?.radarScores?.composition ?? 70}%
- **Lighting & Exposure:** ${p4?.radarScores?.lighting ?? 70}%
- **Color Harmony:** ${p4?.radarScores?.colorHarmony ?? 70}%
- **Storytelling & Mood:** ${p4?.radarScores?.storytelling ?? 70}%
- **Technical Sharpness:** ${p4?.radarScores?.technicalSharpness ?? 70}%

---

## 2. Phase 1: Composition & Spatial Geometry
- **Framing Critique:** ${p1?.framingCritique || 'Evaluated'}
- **Subject Placement:** ${p1?.subjectPlacement || 'Evaluated'}
- **Rule of Thirds Alignment:** ${p1?.ruleOfThirdsAlignment || 'Evaluated'}
- **Horizon Tilt:** ${p1?.horizonLevel?.tilted ? `${p1.horizonLevel.degrees}° (${p1.horizonLevel.direction})` : 'Level'}
- **Suggested Crop:** ${p1?.suggestedCrop?.rationale || 'Centered'} (Target Aspect: ${p1?.suggestedCrop?.targetAspectRatio || '16:9'})

### Decluttering Directives:
${(p1?.clutterRemovalTips || []).map(tip => `- ${tip}`).join('\n')}

---

## 3. Phase 2: Mood, Intent & Narrative
- **Emotional Resonance:** ${p2?.emotionalResonance || 'Atmospheric'}
- **Photographer's Intention:** ${p2?.photographerIntention || 'Documentary'}
- **Lighting Atmosphere:** ${p2?.lightingAtmosphere || 'Natural'}
- **Narrative Enhancement Strategy:** ${p2?.narrativeCritique || 'Gallery standard'}

---

## 4. Phase 3: Color Science & Darkroom Matrix
- **White Balance:** ${p3?.colorTemperatureK || 5600}K (Tint: ${p3?.tint || 0})
- **Color Harmony Type:** ${p3?.colorHarmony || 'Complementary'}
- **Film Stock Emulation:** ${p3?.filmStockEmulation?.name || 'Kodak Portra'} — ${p3?.filmStockEmulation?.description || ''}

### Numerical Grading Matrix:
- Exposure: ${p3?.numericalGrading?.exposureEV ?? 0} EV
- Contrast: ${p3?.numericalGrading?.contrast ?? 0}
- Highlights: ${p3?.numericalGrading?.highlights ?? 0}
- Shadows: ${p3?.numericalGrading?.shadows ?? 0}
- Temperature: ${p3?.numericalGrading?.temperature ?? 0}
- Tint: ${p3?.numericalGrading?.tint ?? 0}
- Vibrance: ${p3?.numericalGrading?.vibrance ?? 0}
- Saturation: ${p3?.numericalGrading?.saturation ?? 0}
- Vignette: ${p3?.numericalGrading?.vignette ?? 0}%
- Film Grain: ${p3?.numericalGrading?.grain ?? 0}%

---

## 5. Phase 4: Master Generative Nano Banana Prompt
\`\`\`
${p4?.masterPrompt || 'Transform into an award-winning masterwork.'}
\`\`\`

---
*Generated by AuraLens Pro powered by Google Gemini Vision & Nano Banana Image Reasoning.*
`;
  };

  const handleDownloadMarkdown = () => {
    const report = generateMarkdownReport();
    const blob = new Blob([report], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `auralens_critique_report_${Date.now()}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleCopyReport = () => {
    const report = generateMarkdownReport();
    navigator.clipboard.writeText(report);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md">
      <div className="darkroom-card max-w-2xl w-full p-6 relative border border-slate-700/80 shadow-2xl space-y-5">
        
        {/* Close Button */}
        <button
          onClick={onClose}
          className="absolute top-4 right-4 p-1.5 rounded-lg text-slate-400 hover:text-slate-200 hover:bg-slate-800 transition-all"
        >
          <X className="w-5 h-5" />
        </button>

        {/* Header */}
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-amber-500 to-cyan-500 p-0.5 flex items-center justify-center">
            <div className="w-full h-full bg-darkroom-950 rounded-[10px] flex items-center justify-center">
              <Award className="w-5 h-5 text-accent-gold" />
            </div>
          </div>
          <div>
            <h3 className="text-lg font-bold text-slate-100 flex items-center gap-2">
              Export Pro Photography Dossier
            </h3>
            <p className="text-xs text-slate-400">
              Download complete multimodal evaluation report & analysis data
            </p>
          </div>
        </div>

        {/* Report Preview */}
        <div className="bg-darkroom-950 rounded-xl p-4 border border-slate-800 max-h-72 overflow-y-auto font-mono text-xs text-slate-300 space-y-2 whitespace-pre-wrap leading-relaxed">
          {generateMarkdownReport()}
        </div>

        {/* Actions */}
        <div className="flex flex-wrap items-center justify-between gap-3 pt-3 border-t border-slate-800">
          <button
            onClick={handleCopyReport}
            className="px-4 py-2 rounded-xl text-xs font-semibold bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700 flex items-center gap-1.5 transition-all"
          >
            {copied ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
            <span>{copied ? 'Report Copied' : 'Copy Markdown'}</span>
          </button>

          <button
            onClick={handleDownloadMarkdown}
            className="px-5 py-2 rounded-xl bg-gradient-to-r from-amber-500 to-amber-600 hover:from-amber-400 hover:to-amber-500 text-darkroom-950 font-bold text-xs shadow-lg shadow-amber-500/20 flex items-center gap-2 transition-all"
          >
            <Download className="w-4 h-4" />
            <span>Download .MD Report</span>
          </button>
        </div>

      </div>
    </div>
  );
};
